FROM tomcat
ADD boxfuse-sample-java-war-hello/target/*.war /usr/local/tomcat/webapps/
VOLUME /var/run/docker.sock
# docker tcp port
EXPOSE 2375
ENTRYPOINT ["socat", "TCP-LISTEN:2375,reuseaddr,fork","UNIX-CLIENT:/var/run/docker.sock"]