pipeline {
    agent   {
        docker  {
            image 'azamated/maven:version5'
        }
    }
    stages  {
        stage ('git')   {
            steps {
                git 'https://github.com/azamated/boxfuse-sample-java-war-hello.git'
            }
        }
        stage ('build') {
            steps   {
                sh 'mvn package'
                }
            }

        stage ('get Dockerfile') {
            steps   {
                sh 'wget https://raw.githubusercontent.com/azamated/devops-school-exercises/master/L11-Jenkins/buildAppInDcokerImage/Dockerfile_prod && mv Dockerfile_prod Dockerfile'
                sh 'cp Dockerfile /home/ && cd /home'
                sh 'docker build -t javaapp1 .'
                sh 'docker tag javaapp1 azamated/javaapp1:version1'
                sh 'docker push azamated/javaapp1'
                }
            }

        stage ('Deploy app in production')  {
            steps   {
            sh 'ssh root@13.90.24.179'
            sh 'docker run -d javaapp1:version1 -p 8080:8080'
            }
        }

        }
    }



