version: '2'
services:
  buillder:
    build: appbuilder
    volumes:
      - appdata:/home/webapp/

  production:
    build: prod
    volumes:
      - /var/lib/docker/volumes/docker-compose_war_depl_appdata/_data/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: