version: '2'
services:
  buillder:
    build: appdata
    volumes:
      - type: volume
        source: appdata
        target: /home/webapp/

  production:
    image: davidcaste/alpine-tomcat:tomcat8
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: appdata
        target: /usr/local/tomcat/webapps/

volumes:
  appdata: