version: '2'
services:
  buillder:
    image: appbuilder
    volumes:
      - appdata:/home/webapp:rw

  production:
    image: prod
    volumes:
      - appdata:/usr/local/tomcat/webapps:rw
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: