version: '2'
services:
  buillder:
    build: appbuilder
    volumes:
      - appdata:/home/webapp/

  production:
    image: accordion/tomcat8:openjdk8
    volumes:
      - appdata:/usr/local/tomcat/webapps:wr
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: