version: '2'
services:
  buillder:
    build: appbuilder
    volumes:
      - appdata:/home/webapp/

  production:
    image: bitnami/tomcat
    volumes:
      - appdata:/bitnami/tomcat/data/hello-1.0.war
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: