version: '2'
services:
  buillder:
    build: builder
    volumes:
      - type: volume
        source: appdata
        target: /home/webapp

  production:
    build: prod
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: appdata
        target: /home/webapp
    depends_on:
      - buillder
volumes:
  appdata: