version: '2'
services:
  buillder:
    build: appdata
    volumes:
      - type: volume
        source: appdata
        target: /home/webapp

  production:
    image: rightctrl/tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: appdata/hello-1.0.war
        target: /usr/local/tomcat/webapps/hello-1.0.war

volumes:
  appdata: