version: '2'
services:
  buillder:
    build: builder
    volumes:
      - type: volume
        source: appdata
        target: /home/webapp

  production:
    build: prod
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/docker-compose_war_depl_appdata/_data/hello-1.0.war
        target: /home/webapp/hello-1.0.war
    depends_on:
      - buillder
volumes:
  appdata: