version: '2'
services:
  buillder:
    build: appbuilder
    volumes:
      - appdata:/home/webapp/

  production:
    build: prod
    volumes:
      - appdata:/home/webapp/
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: