version: '3'
services:
  buillder:
    build: appbuilder
    volumes:
      - appdata:/home/webapp/

  production:
    build: prod
    volumes:
      - type: volume
        source: appdata
        target: /usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: