version: '2'
services:
  buillder:
    build: appbuilder
    volumes:
      - appdata:/home/webapp/

  production:
    image: arm32v6/tomcat
    volumes:
      - appdata:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - buillder

volumes:
  appdata: