pipeline {
    agent any
    tools {
        maven "m3"
    }
    stages {
        stage ('git') {
            steps {
                git 'https://github.com/azamated/boxfuse-sample-java-war-hello.git'
            }
        }
       stage ('build') {
             steps {
                 sh 'mvn package'
             }
        }
       stage ('deploy') {
               steps {
               deploy adapters: [tomcat8(credentialsId: 'ce5dbe5d-9931-400a-aa20-44d45cf1a1e3', path: '', url: 'http://20.185.56.45:8080')], contextPath: 'webapp2', war: '**/*.war'
               }
       }
    }
}