pipeline {
    agent any

    tools {
        terraform "TF"
    }


    environment {
        ACCESS_KEY = credentials('AWS_ACCESS_KEY_ID')
        SECRET_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }


    stages {
        stage ('get TF file') {
            steps {
                sh  'cd /home/azamat/finalProject && wget https://raw.githubusercontent.com/azamated/devops-school-exercises/master/Final%20Project/Terraform/main.tf '
            }
        }

        stage ('Terraform init and Apply') {
            steps {
                sh 'cd /home/azamat/finalProject && terraform init'
                sh "cd /home/azamat/finalProject && terraform plan"
                sh "cd /home/azamat/finalProject && terraform apply -auto-approve"
            }

        }
    }

}