pipeline {
    agent any

    tools {
        tool name: 'org.jenkinsci.plugins.terraform.TerraformInstallation', type: 'terraform'
    }

   parameters {
        string(name: 'WORKSPACE', defaultValue: 'development', description:'setting up workspace for terraform')
    }
    environment {
        TF_HOME = tool('terraform')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
        ACCESS_KEY = credentials('AWS_ACCESS_KEY_ID')
        SECRET_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }


    stages {
        stage ('get TF file') {
            steps {
                sh  '''wget https://raw.githubusercontent.com/azamated/devops-school-exercises/master/Final%20Project/Terraform/main.tf '''
            }
        }

        stage ('Terraform init and Apply') {
            steps {
                sh '''terraform init \
                && terraform plan -var 'access_key=$ACCESS_KEY' -var 'secret_key=$SECRET_KEY' \
                && terraform apply -var 'access_key=$ACCESS_KEY' -var 'secret_key=$SECRET_KEY' -auto-approve '''
            }

        }
    }

}

