pipeline {
    agent any

    tools {
        terraform 'TF'
    }
//String credentialsId = 'awsCredentials'

    stages {
        stage ('get TF file') {
            steps {
                sh  '''cd /home/azamat/FinalProject && wget https://raw.githubusercontent.com/azamated/devops-school-exercises/master/Final%20Project/Terraform/main.tf '''
            }
        }

        stage ('Terraform init and Apply') {
            steps {
                sh 'cd /home/azamat/FinalProject && sudo terraform init'
                sh 'terraform plan && terraform apply -input=false -auto-approve'
            }

        }
    }

}