---
# tasks file for common
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600

- name: Install base software
  apt: name={{item}} state=present
  with_items:
    - mc
    - git