---
# tasks file for build_node
- name: Ensure maven is installed
  apt:
    name: maven
    state: present

- name: Ensure java source code is present
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    version: master
    dest: /tmp/box

- name: Build java source code with maven
  command: mvn package -f /tmp/box

- name: Ensure war artifact is copied to master
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    version: master
    dest: /tmp/box

- name: Ensure war artifact copied to master
  fetch:
    src: /tmp/box/target/hello-1.0.war
    dest: /tmp/hello-1.0.war
    flat: yes
