---
# tasks file for appserver
- name: Install java and tomcat
  apt: name={{item}} state=present
  with_items:
    - default-jdk
    - java8
- name: Ensure war is present
  copy:
    src: /tmp/hello-1.0.war
    dest: /var/lib/tomcat8/webapps/hello-1.0.war