---
- name: install nginx
  hosts: all
  become: yes

  vars:
    source_folder: ./
    dest_folder: /var/www/html

  tasks:
  - name: Ensure nginx package is present
    apt:
      name: nginx
      state: present

  - name: templating nginx
    template: src={{ source_folder }}/index.j2 dest={{ dest_folder }}/index.html mode=0555
    notify: 
      - restart nginx


  handlers:
  - nane: restart nginx
    service: name=nginx state=restarted

