- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my-key
    region: us-east-2
    image: ami-07efac79022b86107

  tasks:
    #Create Security Groups
    - name: Ensure security group exists for Builer node
      ec2_group:
        name: BuilderAppSecurityGroup
        description: Security group for Java App Bilder node with port 22 enabled
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Ensure security group exists for Production node
      ec2_group:
        name: ProdAppSecurityGroup
        description: Security group for Production node with ports 22 and 8080 enabled
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

    #Create Security Groups
    - name: Ensure a builder node is provisioned
      ec2:
        key_name: "{{ key_name }}"
        instance_type: t2.micro
        image: "{{ image }}"
        wait: yes
        id: awsBuilder
        region: "{{ region }}"
        group: BuilderAppSecurityGroup
        count: 1
      register: awsBuilder

    - name: Ensure a production node is provisioned
      ec2:
        key_name: "{{ key_name }}"
        instance_type: t2.micro
        image: "{{ image }}"
        wait: yes
        id: awsProduction
        region: "{{ region }}"
        group: ProdAppSecurityGroup
        count: 1
      register: awsProduction

    #Get AWS instance Public IPs and Add to Ansible Hosts
    - name: Add public IP of builder
      add_host:
        hostname=awsBuilder.instances.public_ip
        groups=awsBuilder
      #with_items: "{{ awsBuilder.instances }}"

    - name: Add public IP of production
      add_host:
        hostname={{ item.public_ip }}
        groups=awsProduction
      with_items: "{{ awsProduction.instances }}"