- hosts: localhost
  connection: local
  gather_facts: False

  vars:
  key_name: my-key
  region: us-east-2
  image: ami-07efac79022b86107

  tasks:

    - name: Provision a builder node
      ec2:
        key_name: "{{ key_name }}"
        instance_type: t2.micro
        image: "{{ image }}"
        wait: yes
        id: dev_build_server3
        region: "{{ region }}"
        group: BuilderAppSecurityGroup
        count: 1