- hosts: localhost
  connection: local
  gather_facts: False



  tasks:


    - name: Provision a builder node
      ec2:
        key_name: my-key
        instance_type: t2.micro
        image: ami-07efac79022b86107
        wait: yes
        id: dev_build_server
        region: us-east-2
        group: BuilderAppSecurityGroup
        count: 1
