#-----------------
#Provision instances
#-----------------
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my-key
    region: us-east-2
    image: ami-07efac79022b86107

  tasks:

    - name: my-key
      ec2_key:
        name: my-key

    - name: Ensure a production node is provisioned
      ec2:
        key_name: "{{ key_name }}"
        instance_type: t2.micro
        image: "{{ image }}"
        wait: yes
        id: awsProdInstance4
        region: "{{ region }}"
        group: EC2SecurityGroup
        count: 1
      register: awsProduction

    #Get AWS instance Public IPs and Add to Ansible Hosts
    - name: Add public IP of awsProduction
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: awsProduction
      loop: "{{ awsProduction.instances }}"

    #Wait until instances start
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ awsProduction.instances }}"

#-----------------
#Install packages
#-----------------
- name: Configure EC2 instance
  hosts: awsProduction
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: False

  #Install packages
  tasks:
    - name: Update repo cache
      raw: apt-get update
    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present
