#-----------------
#Provision instances
#-----------------
- hosts: localhost
  #user: azamat
  gather_facts: False

  vars:
    region: us-east-2
    image: ami-07efac79022b86107

  tasks:
   #Create SSH key pair
    - name: create key pair
      ec2_key:
        name: aws-key
        region: us-east-2
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="/root/.ssh/id_rsa" mode=0600
      when: ec2_key_result.changed

    - name: Ensure a production node is provisioned
      ec2:
        key_name: aws-key
        instance_type: t2.micro
        image: "{{ image }}"
        wait: yes
        id: awsProdInstance8
        region: "{{ region }}"
        group: EC2SecurityGroup
        count: 1
      register: awsProduction

    #Get AWS instance Public IPs and Add to Ansible Hosts
    - name: Add public IP of awsProduction
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: awsProduction
      loop: "{{ awsProduction.instances }}"

    #Wait until instances start
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ awsProduction.instances }}"

#-----------------
#Install packages
#-----------------
- name: Configure EC2 instance
  hosts: awsProduction
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: False

  #Install packages
  tasks:
    - name: Update repo cache
      raw: apt-get update
    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present
