pipeline {
    agent   {
        docker  {
            image 'azamated/builder:version1'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root:docker'
        }
    }
    stages  {
        stage ('git')   {
            steps {
                git 'https://github.com/azamated/boxfuse-sample-java-war-hello.git'
            }
        }
        stage ('build') {
            steps   {
                sh 'mvn package'
                }
            }

        stage ('get Dockerfile') {
            steps   {
                sh 'cd /tmp && wget https://raw.githubusercontent.com/azamated/devops-school-exercises/master/L11-Jenkins/buildAppInDockerImage/Dockerfile_prod'
                sh 'docker build -f /tmp/Dockerfile_prod -t javaapp1 .'
                sh 'docker tag javaapp1 azamated/javaapp1:version2'
                sh 'docker push azamated/javaapp1'
                }
            }

        stage ('Deploy app in production')  {
            steps   {
            sh '''ssh-keyscan -H 13.90.24.179 >> ~/.ssh/known_hosts \
            && ssh root@13.90.24.179 docker login -u azamated -p SKA6XPS6FPOC2RO4 \
            && ssh root@13.90.24.179 docker run -d -p 8080:8080 azamated/javaapp1:version2 '''
            }
        }

        }
    }



