---
- name: install maven
  hosts: dev
  become: yes

  tasks:
  - name: Ensure maven is installed
    apt: 
      name: maven
      state: present

  - name: Ensure jave source code is present
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      version: master
      dest: /tmp/box

  - name: Build java source code with maven
    command: mvn package -f /tmp/box

  - name: Ensure war artifact copied to master
    fetch:
      src: /tmp/box/target/hello-1.0.war
      dest: /tmp/hello-1.0.war
      flat: yes

- name: install tomcat
  hosts: prod
  become: yes

  tasks:
  - name: Ensure default-jdk is installed
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat is installed
    apt:
      name: tomcat8
      state: present

  - name: Ensure war is present
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat8/webapps/hello-1.0.war