---
- name: install maven
  hosts: dev
  become: yes

  tasks:
  - name: Ensure maven is installed
    apt: 
      name: maven
      state: present

  - name: Ensure jave source code is present
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      version: master
      dest: /tmp/box

  - name: Chnage working directory abd run java source code build
    shell: mvn package
    args:
      chdir: /tmp/box

  - name: Ensure war artifact is present on prod
    fetch:
      src: /tmp/box/target/hello-1.0.war
      dest: prod:/tmp/hello-1.0.war

- name: install tomcat
  hosts: prod
  become: yes

  - name: Ensure default-jdk is installed
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat directory exists
    file:
      path: /usr/local/tomcat
      state: directory

  - name: Ensure war is present
    copy:
      src: /tmp/hello-1.0.war
      dest: /usr/local/tomcat/webapps