---
- name: install maven
  hosts: dev
  become: yes

  tasks:
  - name: Ensure maven is installed
    apt: 
      name: maven
      state: present

  - name: Ensure jave source code is present
    git:
      clone: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/

  - name: Chnage working directory abd run java source code build
    shell: mvn package
    args:
      chdir: /tmp/boxfuse-sample-java-war-hello

  - name: Ensure war artifact is present on prod
    copy:
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: prod:/tmp

- name: install tomcat
  hosts: prod
  become: yes

  tasks:
  - name: Ensure Java is installed
    apt:
      name: java
      state: present

  - name: Ensure default-jdk is installed
    apt:
      name: java
      state: present

  - name: Ensure tomcat directory exists
    file:
      path: /usr/local/tomcat
      state: directory

  - name: Ensure war is present
    copy:
      src: /tmp/hello-1.0.war
      dest: /usr/local/tomcat/webapps