FROM ubuntu:latest
# Install pacakges
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y docker.io && apt-get install -y default-jdk && apt-get install -y maven && apt-get install -y git
