pipeline {
    agent   {
        docker  {
            image 'azamated:maven'
        }
    }
    stages  {
        stage ('git')   {
            steps {
                git 'https://github.com/azamated/boxfuse-sample-java-war-hello.git'
            }
        stage ('build') {
            steps   {
                sh 'mvn package'
                sh 'cp /target/*.war'
                }
            }
        stage ('get Dockerfile') {
            steps   {
                sh 'cd /tmp && wget https://raw.githubusercontent.com/azamated/devops-school-exercises/master/L11-Jenkins/build app in temp container/Dockerfile_prod'
                sh 'cp /target/*.war'
                }
            }


        }
    }
}


